playfair_exampleKey1=["STAND",
                   "ERCHB",
                   "KFGIL",
                   "MOPQU",
                   "VWXYZ"]

playfair_exampleKey2=["UNIVE",
                   "RSTYO",
                   "FLDAB",
                   "CGHKM",
                   "PQWXZ"]

simpleSubs_exampleKey1={"A": "Z",
                        "B": "Y",
                        "C": "F",
                        "D": "X",
                        "E": "W",
                        "F": "V",
                        "G": "U",
                        "H": "T",
                        "I": "S",
                        "J": "R",
                        "K": "Q",
                        "L": "P",
                        "M": "O",
                        "N": "N",
                        "O": "M",
                        "P": "L",
                        "Q": "K",
                        "R": "J",
                        "S": "I",
                        "T": "H",
                        "U": "G",
                        "V": "E",
                        "W": "D",
                        "X": "C",
                        "Y": "B",
                        "Z": "A",
                    }


homophonic_exampleKey= {
    "A0": "00",
    "B": "01",
    "C": "02",
    "D": "03",
    "E0": "04",
    "F": "05",
    "G": "06",
    "H": "07",
    "I0": "08",
    "J": "09",
    "K": "10",
    "L": "11",
    "M": "12",
    "N0": "13",
    "O0": "14",
    "P": "15",
    "Q": "16",
    "R": "17",
    "S": "18",
    "T0": "19",
    "U": "20",
    "V": "21",
    "W": "22",
    "X": "23",
    "Y": "24",
    "Z": "25",
    "E1": "26",
    "T1": "27",
    "A1": "28",
    "O1": "29",
    "I1": "30",
    "N1": "31"
}
